services: 
  db: 
    image: postgres:16-bullseye
    container_name: rime-db
    env_file:
      - ./server/.env
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data

volumes: 
  db-data: